### ISSUE TITLE
Please Add API Document

### ISSUE THREAD

**Issue by forewing** [NJUCSE17/JB-Online#37]
Current version of document is lack of API part, please add API document in detail about the format and meaning of request & response.

**Comment by doowzs** [comment]
You can check my WIP in branch 15-redesign-api. API documentation will be powered by swagger.

**Comment by doowzs** [comment]
Currently working on OAuth2 token issue, exchange and documentation.

**Comment by doowzs** [comment]
OAuth2 documentation is done. Will continue to work on forum-related functions.
