### ISSUE TITLE
Bugs about Redundant homework in Notification-email

### ISSUE THREAD

**Issue by Ricky-Ting** [NJUCSE17/JB-Online#42]
For my personally created homework, the email consists of redundant homework. As for default homework, the presence of this bug is unknown.
![screen shot 2019-02-20 at 14 48 26](https://user-images.githubusercontent.com/22109758/53071932-9bc23d80-351e-11e9-8855-ef2d473572b0.png)

**Comment by doowzs** [comment]
Bug recurred in the production environment. The number of PA is wrong.
![smartselect_20190220-145427_termius](https://user-images.githubusercontent.com/33089028/53072318-c365d580-351f-11e9-80c7-2fd73e835cb5.jpg)

**Comment by doowzs** [comment]
Opened branch 42-fix-personal-mail.

**Comment by doowzs** [comment]
Fixed by rewriting the scope that conducts joining with table `course_enroll_records`.
