### ISSUE TITLE
Show recent personal blog posts

### ISSUE THREAD

**Issue by FancyPei** [NJUCSE17/JB-Online#45]
Add a module of newest blogs under / above "Class blogs".

**Comment by doowzs** [comment]
What about add users' page and list users whose blog was recently updated on the homepage?

**Comment by doowzs** [comment]
@zhengzangw wants to integrate RSS feeds from classmates' blogs. Will add this feature in next version.

**Comment by doowzs** [comment]
Completed in the remastered version. 🥂
