### ISSUE TITLE
作业标签排版错误

### ISSUE THREAD

**Issue by forewing** [NJUCSE17/JB-Online#47]
![05C34E9914D15F57AEF059CCBC22EDCF](https://user-images.githubusercontent.com/13747187/55144975-db62f180-517c-11e9-8929-0edb035b8ba6.png)
[https://njujb.com/course/17/assignment/190/asc](url)

**Comment by doowzs** [comment]
感觉像是个默认的表格输入……

重制的版本会引入博客用的自家修改版parser来适配CSS主题
