### ISSUE TITLE
可以随意更改他人用户信息中的是否接受邮件通知一栏

### ISSUE THREAD

**Issue by nju-xy** [NJUCSE17/JB-Online#49]
非权限狗也可以随意更改他人用户信息中的是否接受邮件通知一栏呢！听说只是个前端bug。

**Comment by doowzs** [comment]
`<select>`类型的输入框即使设置成`readonly`也还是可以改变选项；现在这个输入框如果用户无权修改对应内容，则不会显示在界面上。
